[pytest]
pythonpath = .
addopts = --capture=sys
testpaths =
    fy_platform/tests
    contractify/adapter/tests
    testify/adapter/tests
    documentify/adapter/tests
    docify/adapter/tests
    despaghettify/adapter/tests
    dockerify/adapter/tests
    postmanify/adapter/tests
    templatify/adapter/tests
    templatify/tools/tests
