from __future__ import annotations

from pathlib import Path

from architectural_knowledge_db.mcp import MCP_MANIFEST, McpDispatcher
from architectural_knowledge_db.models import AdrInput, RepositoryRegistration
from architectural_knowledge_db.services.consistency import ConsistencyService
from architectural_knowledge_db.services.knowledge import KnowledgeService
from architectural_knowledge_db.services.repositories import RepositoryService
from architectural_knowledge_db.services.staleness import StalenessService
from architectural_knowledge_db.services.uml import UMLService
from tests.conftest import add_project


def test_compute_staleness_reports_review_recommended_for_newer_source_change(conn) -> None:
    add_project(conn, "akdb")
    adr = KnowledgeService(conn).upsert_adr("akdb", AdrInput(adr_id="ADR-0001", title="Old ADR"))
    ConsistencyService(conn).link("akdb", adr["item_uid"], "src/app.py", "governs")
    conn.execute(
        """
        INSERT INTO repositories(repository_id, project_id, local_path)
        VALUES ('repo', 'akdb', '.')
        """
    )
    conn.execute(
        """
        INSERT INTO git_file_history(
          file_history_uid, repository_id, project_id, file_path,
          first_seen_commit_hash, first_seen_at,
          last_changed_commit_hash, last_changed_at,
          change_count, metadata_json
        )
        VALUES ('fh1', 'repo', 'akdb', 'src/app.py', 'a', '2099-01-01T00:00:00Z', 'b', '2099-01-02T00:00:00Z', 2, '{}')
        """
    )

    result = StalenessService(conn).compute_project("akdb")

    assert result["generated"] == 1
    assert result["reports"][0]["status"] == "review_recommended"


def test_status_quo_drift_finds_missing_current_paths_and_symbols_without_git(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    repo = tmp_path / "repo"
    (repo / "src").mkdir(parents=True)
    (repo / "docs").mkdir()
    (repo / "src" / "current_service.py").write_text(
        "class CurrentService:\n    pass\n",
        encoding="utf-8",
    )
    adr_path = repo / "docs" / "ADR-0002.md"
    adr_path.write_text(
        "# ADR-0002: Current contracts\n\n"
        "The implementation uses `CurrentService` and still documents `MissingService` in `src/missing.py`.\n",
        encoding="utf-8",
    )
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="repo", local_path=str(repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="ADR-0002",
            title="Current contracts",
            status="accepted",
            source_uri=str(adr_path),
            raw_source=adr_path.read_text(encoding="utf-8"),
        ),
    )

    result = StalenessService(conn).find_status_quo_drifts("akdb", limit=20)

    assert result["mode"] == "status_quo"
    assert result["candidate_count"] == 2
    references = {finding["reference"]: finding["check_type"] for finding in result["findings"]}
    assert references["src/missing.py"] == "missing_path_reference"
    assert references["MissingService"] == "missing_symbol_reference"
    assert "CurrentService" not in references


def test_status_quo_drift_resolves_neighbor_repository_folder_alias(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    git_repo = tmp_path / "Git"
    website_repo = tmp_path / "Website"
    (git_repo / "docs").mkdir(parents=True)
    website_repo.mkdir()
    (website_repo / "build.py").write_text("def build_site():\n    pass\n", encoding="utf-8")
    adr_path = git_repo / "docs" / "ADR-WEB.md"
    adr_path.write_text(
        "The product website is generated by `Website/build.py`.\n",
        encoding="utf-8",
    )
    repositories = RepositoryService(conn)
    repositories.register_repository(
        "akdb",
        RepositoryRegistration(repository_id="git", local_path=str(git_repo)),
    )
    repositories.register_repository(
        "akdb",
        RepositoryRegistration(repository_id="website", local_path=str(website_repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="ADR-WEB",
            title="Website boundary",
            status="accepted",
            source_uri=str(adr_path),
            raw_source=adr_path.read_text(encoding="utf-8"),
        ),
    )

    result = StalenessService(conn).find_status_quo_drifts("akdb", limit=20)

    references = {finding["reference"]: finding["check_type"] for finding in result["findings"]}
    assert "Website/build.py" not in references


def test_status_quo_drift_reports_unregistered_neighbor_repository_alias(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    git_repo = tmp_path / "Git"
    website_repo = tmp_path / "Website"
    (git_repo / "docs").mkdir(parents=True)
    website_repo.mkdir()
    (website_repo / "build.py").write_text("def build_site():\n    pass\n", encoding="utf-8")
    adr_path = git_repo / "docs" / "ADR-WEB.md"
    adr_path.write_text("The product website is generated by `Website/build.py`.\n", encoding="utf-8")
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="git", local_path=str(git_repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="ADR-WEB",
            title="Website boundary",
            status="accepted",
            source_uri=str(adr_path),
            raw_source=adr_path.read_text(encoding="utf-8"),
        ),
    )

    result = StalenessService(conn).find_status_quo_drifts("akdb", limit=20)

    finding = result["findings"][0]
    assert finding["check_type"] == "external_repository_not_registered"
    assert finding["reference"] == "Website/build.py"
    assert finding["evidence"]["repository_alias"] == "Website"


def test_status_quo_drift_ignores_path_like_fragments_inside_urls(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    adr_path = repo / "docs" / "ADR-UPSTREAM.md"
    adr_path.write_text(
        "See https://github.com/example/project/blob/main/examples/python/EXAMPLES.md for upstream examples.\n",
        encoding="utf-8",
    )
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="repo", local_path=str(repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="ADR-UPSTREAM",
            title="Upstream docs",
            status="accepted",
            source_uri=str(adr_path),
            raw_source=adr_path.read_text(encoding="utf-8"),
        ),
    )

    result = StalenessService(conn).find_status_quo_drifts("akdb", limit=20)

    assert result["findings"] == []


def test_status_quo_drift_classifies_target_state_uml_missing_symbols_as_future_work(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    repo = tmp_path / "repo"
    uml_dir = repo / "UML"
    uml_dir.mkdir(parents=True)
    (uml_dir / "target-state.puml").write_text(
        "@startuml\n"
        "title Runtime Target-State Classes\n"
        "class FuturePanel <<future target Slate>>\n"
        "@enduml\n",
        encoding="utf-8",
    )
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="repo", local_path=str(repo)),
    )
    UMLService(conn).import_diagrams("akdb", uml_dir)

    result = StalenessService(conn).find_status_quo_drifts("akdb", limit=20)

    assert result["findings"][0]["check_type"] == "future_target_symbol_reference"
    assert result["findings"][0]["reference"] == "FuturePanel"


def test_status_quo_drift_classifies_superseded_plan_paths_separately(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    plan_path = repo / "docs" / "plan.md"
    plan_path.write_text(
        "Superseded status, 2026-06-17: do not execute this plan.\n\n"
        "Create `Plugins/Lightning/Source/Lightning/Public/LightningModule.h`.\n",
        encoding="utf-8",
    )
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="repo", local_path=str(repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="PLAN-OLD",
            title="Old Lightning plan",
            status="accepted",
            source_uri=str(plan_path),
            raw_source=plan_path.read_text(encoding="utf-8"),
        ),
    )

    result = StalenessService(conn).find_status_quo_drifts("akdb", limit=20)

    assert result["findings"][0]["check_type"] == "superseded_plan_path_reference"
    assert result["findings"][0]["status"] == "review_recommended"


def test_status_quo_drift_can_be_persisted_and_called_through_mcp(conn, tmp_path: Path) -> None:
    add_project(conn, "akdb")
    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    adr_path = repo / "docs" / "ADR-0003.md"
    adr_path.write_text("References `src/deleted.py`.\n", encoding="utf-8")
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="repo", local_path=str(repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="ADR-0003",
            title="Deleted path",
            status="accepted",
            source_uri=str(adr_path),
            raw_source=adr_path.read_text(encoding="utf-8"),
        ),
    )

    assert any(tool["name"] == "architectural_knowledge_db_find_status_quo_drifts" for tool in MCP_MANIFEST["tools"])
    assert any(tool["name"] == "architectural_knowledge_db_run_drift_check" for tool in MCP_MANIFEST["tools"])
    mcp_result = McpDispatcher(conn).dispatch(
        "architectural_knowledge_db_find_status_quo_drifts",
        {"project_id": "akdb", "limit": 10},
    )
    assert mcp_result["candidate_count"] == 1

    persisted = McpDispatcher(conn).dispatch(
        "architectural_knowledge_db_find_status_quo_drifts",
        {"project_id": "akdb", "limit": 10, "persist": True},
    )
    assert persisted["generated"] == 1
    reports = StalenessService(conn).list_reports("akdb", status_filter=["likely_stale"])
    assert reports[0]["target_type"] == "status_quo_drift"


def test_complete_drift_run_persists_all_status_quo_findings_even_when_return_limited(
    conn,
    tmp_path: Path,
) -> None:
    add_project(conn, "akdb")
    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    adr_path = repo / "docs" / "ADR-0004.md"
    adr_path.write_text(
        "References `src/deleted_a.py` and `src/deleted_b.py`.\n",
        encoding="utf-8",
    )
    RepositoryService(conn).register_repository(
        "akdb",
        RepositoryRegistration(repository_id="repo", local_path=str(repo)),
    )
    KnowledgeService(conn).upsert_adr(
        "akdb",
        AdrInput(
            adr_id="ADR-0004",
            title="Deleted paths",
            status="accepted",
            source_uri=str(adr_path),
            raw_source=adr_path.read_text(encoding="utf-8"),
        ),
    )

    result = StalenessService(conn).run_drift_check("akdb", limit=1)

    assert result["mode"] == "complete_drift_run"
    assert result["modes_run"] == ["status_quo", "git_timeline"]
    assert result["status_quo"]["candidate_count"] == 2
    assert result["status_quo"]["generated_reports"] == 2
    assert len(result["status_quo"]["top_findings"]) == 1
    assert len(StalenessService(conn).list_reports("akdb", status_filter=["likely_stale"])) == 2
